name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          close-pr-message: 'Closing due to inactivity. Reopen if still relevant.'
          days-before-stale: 2
          days-before-close: 3
          only-labels: 'automated pr'