name: Review for README updates

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - uses: ktrnka/update-your-readme@v0.6
        with:
          model-provider: "openai"
          model: gpt-4o-mini-2024-07-18
          api-key: ${{ secrets.OPENAI_API_KEY }}
          readme-file: README.md
