name: Review for README updates

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - uses: ktrnka/update-your-readme@v0.4
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          readme-file: README.md
          debug: "true"
